@baseUrl = http://localhost:3000

GET {{baseUrl}}

### 

GET {{baseUrl}}/users

### 

GET {{baseUrl}}/users/0c259f22-dc81-4cab-9943-a1a04aec5128

###

POST {{baseUrl}}/users
Content-Type: application/json

{ 
	"name": "Smith",
	"username": "smith" 
}
